In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
dataset= pd.read_csv("creditcard.csv")
dataset.head(100),dataset.shape

(    Time        V1        V2        V3        V4        V5        V6  \
 0    0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388
 1    0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361
 2    1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499
 3    1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203
 4    2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921
 ..   ...       ...       ...       ...       ...       ...       ...
 95  64.0 -0.658305  0.406791  2.037461 -0.291298  0.147910 -0.350857
 96  64.0  0.959602  0.370711  0.888613  2.343244  0.352491  1.365515
 97  67.0 -0.653445  0.160225  1.592256  1.296832  0.997175 -0.343000
 98  67.0 -1.494668  0.837241  2.628211  3.145414 -0.609098  0.258495
 99  68.0  1.232996  0.189454  0.491040  0.633673 -0.511574 -0.990609

           V7        V8        V9  ...       V21       V22       V23       V24  \
 0   0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928
 1  -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846
 2   0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281
 3   0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575
 4   0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267
 ..       ...       ...       ...  ...       ...       ...       ...       ...
 95  0.945373 -0.172560  0.025133  ... -0.156096 -0.238805  0.089877  0.421195
 96 -0.277771  0.516053 -0.700929  ... -0.155547 -0.403239  0.356504 -0.696881
 97  0.469937 -0.132470 -0.197794  ...  0.038363  0.336449 -0.014883  0.102959
 98 -0.012189  0.102136 -0.286164  ... -0.140047  0.355044  0.332720  0.718193
 99  0.066240 -0.196940  0.075921  ... -0.251566 -0.770139  0.125998  0.369627

          V25       V26       V27       V28  Amount  Class
 0   0.128539 -0.189115  0.133558 -0.021053  149.62      0
 1   0.167170  0.125895 -0.008983  0.014724    2.69      0
 2  -0.327642 -0.139097 -0.055353 -0.059752  378.66      0
 3   0.647376 -0.221929  0.062723  0.061458  123.50      0
 4  -0.206010  0.502292  0.219422  0.215153   69.99      0
 ..       ...       ...       ...       ...     ...    ...
 95 -0.352487  0.074783 -0.094192 -0.092493   54.99      0
 96 -0.198718 -0.220268  0.068546  0.020797    7.55      0
 97 -0.265322 -0.348637  0.011238 -0.049478   19.85      0
 98 -0.219366  0.118927 -0.317486 -0.340783   28.28      0
 99  0.205598  0.094062 -0.033138  0.020990   15.99      0

 [100 rows x 31 columns],
 (284807, 31))

In [3]:
dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [4]:
dataset.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
dataset.info(),dataset.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

(None,
                 Time            V1            V2            V3            V4  \
 count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
 mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15
 std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00
 min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00
 25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01
 50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02
 75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01
 max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01

                  V5            V6            V7            V8            V9  \
 count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
 mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15
 std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00
 min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01
 25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01
 50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02
 75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01
 max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01

        ...           V21           V22           V23           V24  \
 count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
 mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15
 std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01
 min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00
 25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01
 50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02
 75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01
 max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00

                 V25           V26           V27           V28         Amount  \
 count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000
 mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619
 std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109
 min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000
 25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000
 50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000
 75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000
 max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000

                Class
 count  284807.000000
 mean        0.001727
 std         0.041527
 min         0.000000
 25%         0.000000
 50%         0.000000
 75%         0.000000
 max         1.000000

 [8 rows x 31 columns])

In [6]:
dataset.value_counts()

Time      V1          V2          V3         V4         V5         V6         V7          V8          V9         V10        V11        V12        V13        V14        V15        V16        V17        V18        V19        V20        V21         V22        V23        V24        V25        V26        V27        V28        Amount  Class
163152.0  -1.196037    1.585949    2.883976   3.378471   1.511706   3.717077   0.585362   -0.156001    0.122648   4.217934   1.385525  -0.709405  -0.256168  -1.564352   1.693218  -0.785210  -0.228008  -0.412833   0.234834   1.375790  -0.370294    0.524395  -0.355170  -0.869790  -0.133198   0.327804  -0.035702  -0.858197  7.56    0        18
          -1.203617    1.574009    2.889277   3.381404   1.538663   3.698747   0.560211   -0.150911    0.124136   4.220998   1.384569  -0.706897  -0.256274  -1.562583   1.692915  -0.787338  -0.226776  -0.412354   0.234322   1.385597  -0.366727    0.522223  -0.357329  -0.870174  -0.134166   0.327019  -0.042648  -0.855262  1.51    0        18
43153.0   -2.086016    2.203265    1.654339   2.941050  -1.683045   0.529728  -1.352162    1.793449   -0.723686   0.600365  -0.982212  -0.551636  -1.337000   0.834403   1.251862   0.033455   1.067978   0.160510   0.213087   0.079002   0.216444    0.567241  -0.035345   0.370201   0.157378   0.440341   0.210230   0.090558  0.76    0         9
170731.0   2.033492    0.766969   -2.107555   3.631952   1.348594  -0.499907   0.945159   -0.286392   -1.370581   1.653073  -1.600434  -1.510901  -2.143280   1.189850  -0.875588   0.175808  -0.419433  -0.464717  -1.414528  -0.430560   0.241894    0.658545  -0.102644   0.580535   0.643637   0.347240  -0.116618  -0.078601  0.76    0         9
68207.0   -13.192671   12.785971  -9.906650   3.320337  -4.801176   5.760059  -18.750889  -37.353443  -0.391540  -5.052502   4.406806  -4.610756  -1.909488  -9.072711  -0.226074  -6.211557  -6.248145  -3.149247   0.051576  -3.493050   27.202839  -8.887017   5.303607  -0.639435   0.263203  -0.108877   1.269566   0.939407  1.00    1         6
                                                                                                                                                                                                                                                                                                                                                    ..
65149.0   -0.608037    0.277482    2.333740   0.713876  -0.686327   0.424502   0.158410    0.277078    0.005665  -0.574444  -0.383596   0.063757   0.435809  -0.294166   1.561564   0.430549  -0.512260   0.321857  -1.089111   0.192164   0.425425    1.077523   0.095700   0.080007  -0.087784  -0.253436   0.077868   0.055774  115.98  0         1
           0.890428   -0.914533    0.916273   0.533497  -1.417793  -0.283902  -0.520284    0.002223   -1.050330   0.827726   1.336306   0.961705   0.778165   0.101997   0.352339  -0.892199  -0.538873   1.792922  -1.092627  -0.119284  -0.239564   -0.634749  -0.018377   0.482486   0.102384  -0.559266   0.040121   0.067240  192.05  0         1
65150.0   -0.819167    1.289630    1.155617  -0.356589   0.742668  -1.179886   1.114827   -0.105033   -1.169136  -1.218791   1.841286   0.558376   0.081792  -1.028918  -0.400824   0.722658   0.402985   0.613975  -0.605494  -0.014715  -0.011025   -0.125263  -0.385443   0.449483   0.536560   0.252429  -0.020876   0.072608  0.76    0         1
          -0.283939    1.355339    0.553398   0.255501   0.561040  -1.338352   1.056880   -0.229176   -0.738105  -1.157676   0.000759  -0.543236  -0.313497  -1.370815   0.770587   0.452886   1.064176   0.458320  -0.199074  -0.019922  -0.076192   -0.211969  -0.256209   0.259185   0.096589   0.327896   0.021232   0.083294  0.76    0         1
172792.0  -0.533413   -0.189733    0.703337  -0.506271  -0.012546  -0.649617   1.577006   -0.414650    0.486180  -0.915427  -1.040458  -0.031513  -0.188093  -0.084316   0.041333  -0.302620  -0.660377   0.167430  -0.256117   0.382948   0.261057    0.643078   0.376777   0.008797  -0.473649  -0.818267  -0.002415   0.013649  217.00  0         1
Length: 283726, dtype: int64

In [7]:
x= dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values

In [8]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25, random_state=0)

In [9]:
x_train,y_train

(array([[ 1.30747000e+05,  2.04716304e+00,  1.07986610e-01, ...,
         -8.50246556e-02, -8.42920007e-02,  7.70000000e-01],
        [ 8.13440000e+04,  1.28240449e+00,  4.59864448e-01, ...,
         -1.01678633e-02, -5.33248686e-03,  1.79000000e+00],
        [ 1.59004000e+05, -4.14862511e-01,  1.20257796e-02, ...,
          2.37627707e-01,  2.04342556e-01,  5.95000000e+00],
        ...,
        [ 7.66160000e+04,  1.51260229e+00, -9.49435315e-01, ...,
         -1.41537086e-03,  3.66494418e-03,  3.49000000e+01],
        [ 9.72530000e+04,  1.79886333e+00, -1.69979073e+00, ...,
         -3.36155803e-02, -3.24705125e-02,  1.71310000e+02],
        [ 7.48870000e+04, -5.89399721e-01,  7.47828393e-01, ...,
          8.65917860e-02,  1.18083774e-01,  1.59900000e+01]]),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [10]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train[:,-1:] = sc_x.fit_transform(x_train[:,-1:])
x_train[:,:1]= sc_x.fit_transform(x_train[:,:1])

x_test[:,-1:] = sc_x.transform(x_test[:,-1:])
x_test[:,:1]= sc_x.transform(x_test[:,:1])

In [ ]:
from sklearn.svm import SVC
model = SVC(kernel="rbf",random_state=1)
model.fit(x_train,y_train)

In [ ]:
y_pred = model.predict(x_test)

from sklearn.metric import confusion_matrix, accuracy_score

confusion_matrix(y_test,y_pred),accuracy_score(y_test,y_pred)